---
deployment:
  tasks:
    - export DEPLOYPATH=/home/medcarec/repositories/simona_website
    -/assets -R img $DEPLOYPATH
    -/css style.css $DEPLOYPATH
    -/js scripts.js $DEPLOYPATH
    - index.html $DEPLOYPATH
