---
deployment:
  tasks:
    - export DEPLOYPATH=/home/medcarec/repositories
    - /simona_website/assets -R img $DEPLOYPATH
    - /simona_website/css style.css $DEPLOYPATH
    - /simona_website/js scripts.js $DEPLOYPATH
    - /simona_website index.html $DEPLOYPATH
