---
deployment:
  tasks:
    - export DEPLOYPATH=/home/medcarec/repositories/simona_website
    - /bin/cp -R assets/img $DEPLOYPATH
    - /bin/cp css/style.css $DEPLOYPATH
    - /bin/cp js/scripts.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
